create database saledb;
use saledb;

create table category (id int not null, name varchar(128), primary key (id));
create table product (id int not null, category_id int, name varchar(128), price decimal(6,2), foreign key (category_id) references category(id), primary key (id));
create table purchase (id int not null auto_increment, client_name varchar(254), client_email varchar(128), client_card int8, client_cv2 int, client_street varchar(254), client_postalcode varchar(65), client_city varchar(128), primary key (id));
create table cart (purchase_id int not null, product_id int not null, quantity int, foreign key (purchase_id) references purchase(id), foreign key (product_id) references product(id), primary key (purchase_id, product_id));

insert into category (id, name) values (1, 'Fresh vegetables');
insert into category (id, name) values (2, 'Fresh fruits');
insert into category (id, name) values (3, 'Refrigerated');
insert into category (id, name) values (4, 'Frozen');
insert into category (id, name) values (5, 'Sauces');
insert into category (id, name) values (6, 'Various groceries');
insert into category (id, name) values (7, 'Canned foods');
insert into category (id, name) values (8, 'Spices & herbs');
insert into category (id, name) values (9, 'Dairy');
insert into category (id, name) values (10, 'Cheese');
insert into category (id, name) values (11, 'Meat');
insert into category (id, name) values (12, 'Seafood');
insert into category (id, name) values (13, 'Beverages');
insert into category (id, name) values (14, 'Baked goods');
insert into category (id, name) values (15, 'Baking');
insert into category (id, name) values (16, 'Snacks');
insert into category (id, name) values (17, 'Themed meals');
insert into category (id, name) values (18, 'Baby stuff');
insert into category (id, name) values (19, 'Pets');
insert into category (id, name) values (20, 'Personal care');
insert into category (id, name) values (21, 'Medicine');
insert into category (id, name) values (22, 'Kitchen');
insert into category (id, name) values (23, 'Cleaning products');
insert into category (id, name) values (24, 'Office supplies');
insert into category (id, name) values (25, 'Other stuff');
insert into category (id, name) values (26, 'Carcinogens');

insert into product (id, category_id, name, price) values (1, 1, 'Asparagus', 4.2);
insert into product (id, category_id, name, price) values (2, 1, 'Broccoli', 1.2);
insert into product (id, category_id, name, price) values (3, 1, 'Carrots', 3.2);
insert into product (id, category_id, name, price) values (4, 1, 'Cauliflower', 3.2);
insert into product (id, category_id, name, price) values (5, 1, 'Celery', 6.2);
insert into product (id, category_id, name, price) values (6, 1, 'Corn', 1.2);
insert into product (id, category_id, name, price) values (7, 1, 'Cucumbers', 3.2);
insert into product (id, category_id, name, price) values (8, 1, 'Lettuce', 6.2);
insert into product (id, category_id, name, price) values (9, 1, 'Mushrooms', 4.2);
insert into product (id, category_id, name, price) values (10, 1, 'Onions', 4.2);
insert into product (id, category_id, name, price) values (11, 1, 'Peppers', 5.2);
insert into product (id, category_id, name, price) values (12, 1, 'Potatoes', 3.2);
insert into product (id, category_id, name, price) values (13, 1, 'Spinach', 3.2);
insert into product (id, category_id, name, price) values (14, 1, 'Squash', 2.2);
insert into product (id, category_id, name, price) values (15, 1, 'Zucchini', 2.2);
insert into product (id, category_id, name, price) values (16, 1, 'Tomatoes', 2.2);
insert into product (id, category_id, name, price) values (17, 2, 'Apples', 10.1);
insert into product (id, category_id, name, price) values (18, 2, 'Avocados', 8.1);
insert into product (id, category_id, name, price) values (19, 2, 'Bananas', 9.1);
insert into product (id, category_id, name, price) values (20, 2, 'Berries', 5.1);
insert into product (id, category_id, name, price) values (21, 2, 'Cherries', 2.1);
insert into product (id, category_id, name, price) values (22, 2, 'Grapefruit', 13.1);
insert into product (id, category_id, name, price) values (23, 2, 'Grapes', 5.1);
insert into product (id, category_id, name, price) values (24, 2, 'Kiwis', 2.1);
insert into product (id, category_id, name, price) values (25, 2, 'Lemons', 4.1);
insert into product (id, category_id, name, price) values (26, 2, 'Melon', 2.1);
insert into product (id, category_id, name, price) values (27, 2, 'Oranges', 10.1);
insert into product (id, category_id, name, price) values (28, 2, 'Peaches', 14.1);
insert into product (id, category_id, name, price) values (29, 2, 'Nectarines', 2.1);
insert into product (id, category_id, name, price) values (30, 2, 'Pears', 7.1);
insert into product (id, category_id, name, price) values (31, 2, 'Plums', 14.1);
insert into product (id, category_id, name, price) values (32, 3, 'Bagels', 3.1);
insert into product (id, category_id, name, price) values (33, 3, 'Chip dip', 5.1);
insert into product (id, category_id, name, price) values (34, 3, 'English muffins', 8.1);
insert into product (id, category_id, name, price) values (35, 3, 'Eggs', 3.1);
insert into product (id, category_id, name, price) values (36, 3, 'Fruit juice', 8.1);
insert into product (id, category_id, name, price) values (37, 3, 'Hummus', 2.1);
insert into product (id, category_id, name, price) values (38, 3, 'Ready-bake breads', 8.1);
insert into product (id, category_id, name, price) values (39, 3, 'Tofu', 5.1);
insert into product (id, category_id, name, price) values (40, 3, 'Tortillas', 6.1);
insert into product (id, category_id, name, price) values (41, 4, 'Breakfasts', 17.2);
insert into product (id, category_id, name, price) values (42, 4, 'Burritos', 18.2);
insert into product (id, category_id, name, price) values (43, 4, 'Fish sticks', 16.2);
insert into product (id, category_id, name, price) values (44, 4, 'Ice cream', 20.2);
insert into product (id, category_id, name, price) values (45, 4, 'Juice concentrate', 20.2);
insert into product (id, category_id, name, price) values (46, 4, 'Pizza', 24.2);
insert into product (id, category_id, name, price) values (47, 4, 'Popsicles', 17.2);
insert into product (id, category_id, name, price) values (48, 4, 'Fries', 13.2);
insert into product (id, category_id, name, price) values (49, 4, 'TV dinners', 11.2);
insert into product (id, category_id, name, price) values (50, 4, 'Vegetables', 21.2);
insert into product (id, category_id, name, price) values (51, 4, 'Veggie burgers', 24.2);
insert into product (id, category_id, name, price) values (52, 5, 'BBQ sauce', 7.2);
insert into product (id, category_id, name, price) values (53, 5, 'Gravy', 7.2);
insert into product (id, category_id, name, price) values (54, 5, 'Honey', 6.2);
insert into product (id, category_id, name, price) values (55, 5, 'Hot sauce', 6.2);
insert into product (id, category_id, name, price) values (56, 5, 'Jelly', 6.2);
insert into product (id, category_id, name, price) values (57, 5, 'Ketchup', 6.2);
insert into product (id, category_id, name, price) values (58, 5, 'Mustard', 7.2);
insert into product (id, category_id, name, price) values (59, 5, 'Mayonnaise', 7.2);
insert into product (id, category_id, name, price) values (60, 5, 'Pasta sauce', 5.2);
insert into product (id, category_id, name, price) values (61, 5, 'Relish', 5.2);
insert into product (id, category_id, name, price) values (62, 5, 'Salad dressing', 6.2);
insert into product (id, category_id, name, price) values (63, 5, 'Salsa', 6.2);
insert into product (id, category_id, name, price) values (64, 5, 'Soy sauce', 8.2);
insert into product (id, category_id, name, price) values (65, 5, 'Steak sauce', 5.2);
insert into product (id, category_id, name, price) values (66, 5, 'Syrup', 6.2);
insert into product (id, category_id, name, price) values (67, 5, 'Worcestershire sauce', 5.2);
insert into product (id, category_id, name, price) values (68, 6, 'Bouillon cubes', 10.5);
insert into product (id, category_id, name, price) values (69, 6, 'Cereal', 12.5);
insert into product (id, category_id, name, price) values (70, 6, 'Coffee', 9.5);
insert into product (id, category_id, name, price) values (71, 6, 'Instant potatoes', 13.5);
insert into product (id, category_id, name, price) values (72, 6, 'Lime juice', 11.5);
insert into product (id, category_id, name, price) values (73, 6, 'Mac & cheese', 3.5);
insert into product (id, category_id, name, price) values (74, 6, 'Olive oil', 5.5);
insert into product (id, category_id, name, price) values (75, 6, 'Pancake / Waffle mix', 11.5);
insert into product (id, category_id, name, price) values (76, 6, 'Pasta', 9.5);
insert into product (id, category_id, name, price) values (77, 6, 'Peanut butter', 12.5);
insert into product (id, category_id, name, price) values (78, 6, 'Pickles', 11.5);
insert into product (id, category_id, name, price) values (79, 6, 'Rice', 4.5);
insert into product (id, category_id, name, price) values (80, 6, 'Tea', 10.5);
insert into product (id, category_id, name, price) values (81, 6, 'Vegetable oil', 10.5);
insert into product (id, category_id, name, price) values (82, 6, 'Vinegar', 11.5);
insert into product (id, category_id, name, price) values (83, 7, 'Applesauce', 5.8);
insert into product (id, category_id, name, price) values (84, 7, 'Baked beans', 6.8);
insert into product (id, category_id, name, price) values (85, 7, 'Chili', 5.8);
insert into product (id, category_id, name, price) values (86, 7, 'Fruit', 5.8);
insert into product (id, category_id, name, price) values (87, 7, 'Olives', 4.8);
insert into product (id, category_id, name, price) values (88, 7, 'Tinned meats', 6.8);
insert into product (id, category_id, name, price) values (89, 7, 'Tuna / Chicken', 6.8);
insert into product (id, category_id, name, price) values (90, 7, 'Soups', 4.8);
insert into product (id, category_id, name, price) values (91, 7, 'Tomatoes', 6.8);
insert into product (id, category_id, name, price) values (92, 7, 'Veggies', 6.8);
insert into product (id, category_id, name, price) values (93, 8, 'Basil', 13.1);
insert into product (id, category_id, name, price) values (94, 8, 'Black pepper', 13.1);
insert into product (id, category_id, name, price) values (95, 8, 'Cilantro', 11.1);
insert into product (id, category_id, name, price) values (96, 8, 'Cinnamon', 15.1);
insert into product (id, category_id, name, price) values (97, 8, 'Garlic', 9.1);
insert into product (id, category_id, name, price) values (98, 8, 'Ginger', 13.1);
insert into product (id, category_id, name, price) values (99, 8, 'Mint', 12.1);
insert into product (id, category_id, name, price) values (100, 8, 'Oregano', 10.1);
insert into product (id, category_id, name, price) values (101, 8, 'Paprika', 15.1);
insert into product (id, category_id, name, price) values (102, 8, 'Parsley', 13.1);
insert into product (id, category_id, name, price) values (103, 8, 'Red pepper', 12.1);
insert into product (id, category_id, name, price) values (104, 8, 'Salt', 15.1);
insert into product (id, category_id, name, price) values (105, 8, 'Spice mix', 13.1);
insert into product (id, category_id, name, price) values (106, 8, 'Vanilla extract', 11.1);
insert into product (id, category_id, name, price) values (107, 9, 'Butter / Margarine', 20.5);
insert into product (id, category_id, name, price) values (108, 9, 'Cottage cheese', 4.5);
insert into product (id, category_id, name, price) values (109, 9, 'Half & half', 23.5);
insert into product (id, category_id, name, price) values (110, 9, 'Milk', 22.5);
insert into product (id, category_id, name, price) values (111, 9, 'Sour cream', 2.5);
insert into product (id, category_id, name, price) values (112, 9, 'Whipped cream', 12.5);
insert into product (id, category_id, name, price) values (113, 9, 'Yogurt', 18.5);
insert into product (id, category_id, name, price) values (114, 10, 'Bleu cheese', 8.5);
insert into product (id, category_id, name, price) values (115, 10, 'Cheddar', 4.5);
insert into product (id, category_id, name, price) values (116, 10, 'Cottage cheese', 6.5);
insert into product (id, category_id, name, price) values (117, 10, 'Cream cheese', 4.5);
insert into product (id, category_id, name, price) values (118, 10, 'Feta', 12.5);
insert into product (id, category_id, name, price) values (119, 10, 'Goat cheese', 4.5);
insert into product (id, category_id, name, price) values (120, 10, 'Mozzarella / Provolone', 11.5);
insert into product (id, category_id, name, price) values (121, 10, 'Parmesan', 11.5);
insert into product (id, category_id, name, price) values (122, 10, 'Provolone', 12.5);
insert into product (id, category_id, name, price) values (123, 10, 'Ricotta', 4.5);
insert into product (id, category_id, name, price) values (124, 10, 'Sandwich slices', 13.5);
insert into product (id, category_id, name, price) values (125, 10, 'Swiss', 13.5);
insert into product (id, category_id, name, price) values (126, 11, 'Bacon / Sausage', 18.5);
insert into product (id, category_id, name, price) values (127, 11, 'Beef', 9.5);
insert into product (id, category_id, name, price) values (128, 11, 'Chicken', 15.5);
insert into product (id, category_id, name, price) values (129, 11, 'Ground beef / Turkey', 16.5);
insert into product (id, category_id, name, price) values (130, 11, 'Ham / Pork', 12.5);
insert into product (id, category_id, name, price) values (131, 11, 'Hot dogs', 13.5);
insert into product (id, category_id, name, price) values (132, 11, 'Lunchmeat', 12.5);
insert into product (id, category_id, name, price) values (133, 11, 'Turkey', 13.5);
insert into product (id, category_id, name, price) values (134, 12, 'Catfish', 11.2);
insert into product (id, category_id, name, price) values (135, 12, 'Crab', 10.2);
insert into product (id, category_id, name, price) values (136, 12, 'Lobster', 9.2);
insert into product (id, category_id, name, price) values (137, 12, 'Mussels', 13.2);
insert into product (id, category_id, name, price) values (138, 12, 'Oysters', 13.2);
insert into product (id, category_id, name, price) values (139, 12, 'Salmon', 8.2);
insert into product (id, category_id, name, price) values (140, 12, 'Shrimp', 9.2);
insert into product (id, category_id, name, price) values (141, 12, 'Tilapia', 10.2);
insert into product (id, category_id, name, price) values (142, 12, 'Tuna', 10.2);
insert into product (id, category_id, name, price) values (143, 13, 'Beer', 2.5);
insert into product (id, category_id, name, price) values (144, 13, 'Club soda / Tonic', 3.5);
insert into product (id, category_id, name, price) values (145, 13, 'Champagne', 3.5);
insert into product (id, category_id, name, price) values (146, 13, 'Gin', 2.5);
insert into product (id, category_id, name, price) values (147, 13, 'Juice', 1.5);
insert into product (id, category_id, name, price) values (148, 13, 'Mixers', 2.5);
insert into product (id, category_id, name, price) values (149, 13, 'Red wine / White wine', 1.5);
insert into product (id, category_id, name, price) values (150, 13, 'Rum', 3.5);
insert into product (id, category_id, name, price) values (151, 13, 'Saké', 1.5);
insert into product (id, category_id, name, price) values (152, 13, 'Soda pop', 3.5);
insert into product (id, category_id, name, price) values (153, 13, 'Sports drink', 1.5);
insert into product (id, category_id, name, price) values (154, 13, 'Whiskey', 3.5);
insert into product (id, category_id, name, price) values (155, 13, 'Vodka', 2.5);
insert into product (id, category_id, name, price) values (156, 14, 'Bagels / Croissants', 4.9);
insert into product (id, category_id, name, price) values (157, 14, 'Buns / Rolls', 4.9);
insert into product (id, category_id, name, price) values (158, 14, 'Cake / Cookies', 6.9);
insert into product (id, category_id, name, price) values (159, 14, 'Donuts / Pastries', 4.9);
insert into product (id, category_id, name, price) values (160, 14, 'Fresh bread', 4.9);
insert into product (id, category_id, name, price) values (161, 14, 'Sliced bread', 7.9);
insert into product (id, category_id, name, price) values (162, 14, 'Pie', 6.9);
insert into product (id, category_id, name, price) values (163, 14, 'Pita bread', 5.9);
insert into product (id, category_id, name, price) values (164, 15, 'Baking powder / Soda', 4.7);
insert into product (id, category_id, name, price) values (165, 15, 'Bread crumbs', 7.7);
insert into product (id, category_id, name, price) values (166, 15, 'Cake / Brownie mix', 6.7);
insert into product (id, category_id, name, price) values (167, 15, 'Cake icing', 10.7);
insert into product (id, category_id, name, price) values (168, 15, 'Chocolate chips', 6.7);
insert into product (id, category_id, name, price) values (169, 15, 'Cocoa', 5.7);
insert into product (id, category_id, name, price) values (170, 15, 'Flour', 10.7);
insert into product (id, category_id, name, price) values (171, 15, 'Shortening', 3.7);
insert into product (id, category_id, name, price) values (172, 15, 'Sugar', 9.7);
insert into product (id, category_id, name, price) values (173, 15, 'Sugar substitute', 5.7);
insert into product (id, category_id, name, price) values (174, 15, 'Yeast', 7.7);
insert into product (id, category_id, name, price) values (175, 16, 'Candy / Gum', 5.1);
insert into product (id, category_id, name, price) values (176, 16, 'Cookies', 4.1);
insert into product (id, category_id, name, price) values (177, 16, 'Crackers', 3.1);
insert into product (id, category_id, name, price) values (178, 16, 'Dried fruit', 3.1);
insert into product (id, category_id, name, price) values (179, 16, 'Granola bars / Mix', 4.1);
insert into product (id, category_id, name, price) values (180, 16, 'Nuts / Seeds', 4.1);
insert into product (id, category_id, name, price) values (181, 16, 'Oatmeal', 3.1);
insert into product (id, category_id, name, price) values (182, 16, 'Popcorn', 4.1);
insert into product (id, category_id, name, price) values (183, 16, 'Potato / Corn chips', 5.1);
insert into product (id, category_id, name, price) values (184, 16, 'Pretzels', 4.1);
insert into product (id, category_id, name, price) values (185, 17, 'Burger night', 17.2);
insert into product (id, category_id, name, price) values (186, 17, 'Chili night', 9.2);
insert into product (id, category_id, name, price) values (187, 17, 'Pizza night', 9.2);
insert into product (id, category_id, name, price) values (188, 17, 'Spaghetti night', 10.2);
insert into product (id, category_id, name, price) values (189, 17, 'Taco night', 7.2);
insert into product (id, category_id, name, price) values (190, 17, 'Take-out deli food', 12.2);
insert into product (id, category_id, name, price) values (191, 18, 'Baby food', 22.2);
insert into product (id, category_id, name, price) values (192, 18, 'Diapers', 24.2);
insert into product (id, category_id, name, price) values (193, 18, 'Formula', 15.2);
insert into product (id, category_id, name, price) values (194, 18, 'Lotion', 9.2);
insert into product (id, category_id, name, price) values (195, 18, 'Baby wash', 8.2);
insert into product (id, category_id, name, price) values (196, 18, 'Wipes', 20.2);
insert into product (id, category_id, name, price) values (197, 19, 'Cat food / Treats', 23.1);
insert into product (id, category_id, name, price) values (198, 19, 'Cat litter', 18.1);
insert into product (id, category_id, name, price) values (199, 19, 'Dog food / Treats', 8.1);
insert into product (id, category_id, name, price) values (200, 19, 'Flea treatment', 17.1);
insert into product (id, category_id, name, price) values (201, 19, 'Pet shampoo', 6.1);
insert into product (id, category_id, name, price) values (202, 20, 'Antiperspirant / Deodorant', 11.9);
insert into product (id, category_id, name, price) values (203, 20, 'Bath soap', 18.9);
insert into product (id, category_id, name, price) values (204, 20, 'Hand soap', 13.9);
insert into product (id, category_id, name, price) values (205, 20, 'Condoms / Other b.c.', 14.9);
insert into product (id, category_id, name, price) values (206, 20, 'Cosmetics', 18.9);
insert into product (id, category_id, name, price) values (207, 20, 'Cotton swabs / Balls', 10.9);
insert into product (id, category_id, name, price) values (208, 20, 'Facial cleanser', 14.9);
insert into product (id, category_id, name, price) values (209, 20, 'Facial tissue', 16.9);
insert into product (id, category_id, name, price) values (210, 20, 'Feminine products', 18.9);
insert into product (id, category_id, name, price) values (211, 20, 'Floss', 12.9);
insert into product (id, category_id, name, price) values (212, 20, 'Hair gel / Spray', 8.9);
insert into product (id, category_id, name, price) values (213, 20, 'Lip balm', 16.9);
insert into product (id, category_id, name, price) values (214, 20, 'Moisturizing lotion', 6.9);
insert into product (id, category_id, name, price) values (215, 20, 'Mouthwash', 6.9);
insert into product (id, category_id, name, price) values (216, 20, 'Razors / Shaving cream', 16.9);
insert into product (id, category_id, name, price) values (217, 20, 'Shampoo / Conditioner', 3.9);
insert into product (id, category_id, name, price) values (218, 20, 'Sunblock', 10.9);
insert into product (id, category_id, name, price) values (219, 20, 'Toilet paper', 15.9);
insert into product (id, category_id, name, price) values (220, 20, 'Toothpaste', 18.9);
insert into product (id, category_id, name, price) values (221, 20, 'Vitamins / Supplements', 6.9);
insert into product (id, category_id, name, price) values (222, 21, 'Allergy', 25.1);
insert into product (id, category_id, name, price) values (223, 21, 'AllergyAntibiotic', 6.1);
insert into product (id, category_id, name, price) values (224, 21, 'AllergyAntidiarrheal', 13.1);
insert into product (id, category_id, name, price) values (225, 21, 'AllergyAspirin', 15.1);
insert into product (id, category_id, name, price) values (226, 21, 'AllergyAntacid', 10.1);
insert into product (id, category_id, name, price) values (227, 21, 'AllergyBand-aids / Medical', 7.1);
insert into product (id, category_id, name, price) values (228, 21, 'AllergyCold / Flu / Sinus', 14.1);
insert into product (id, category_id, name, price) values (229, 21, 'AllergyPain reliever', 11.1);
insert into product (id, category_id, name, price) values (230, 21, 'AllergyPrescription pick-up', 30.1);
insert into product (id, category_id, name, price) values (231, 22, 'Aluminum foil', 24.7);
insert into product (id, category_id, name, price) values (232, 22, 'Napkins', 14.7);
insert into product (id, category_id, name, price) values (233, 22, 'Non-stick spray', 8.7);
insert into product (id, category_id, name, price) values (234, 22, 'Paper towels', 12.7);
insert into product (id, category_id, name, price) values (235, 22, 'Plastic wrap', 22.7);
insert into product (id, category_id, name, price) values (236, 22, 'Sandwich / Freezer bags', 25.7);
insert into product (id, category_id, name, price) values (237, 22, 'Wax paper', 13.7);
insert into product (id, category_id, name, price) values (238, 23, 'Air freshener', 13.1);
insert into product (id, category_id, name, price) values (239, 23, 'Bathroom cleaner', 13.1);
insert into product (id, category_id, name, price) values (240, 23, 'Bleach / Detergent', 20.1);
insert into product (id, category_id, name, price) values (241, 23, 'Dish / Dishwasher soap', 17.1);
insert into product (id, category_id, name, price) values (242, 23, 'Garbage bags', 21.1);
insert into product (id, category_id, name, price) values (243, 23, 'Glass cleaner', 15.1);
insert into product (id, category_id, name, price) values (244, 23, 'Mop head / Vacuum bags', 18.1);
insert into product (id, category_id, name, price) values (245, 23, 'Sponges / Scrubbers', 13.1);
insert into product (id, category_id, name, price) values (246, 24, 'CDRs / DVDRs', 18.2);
insert into product (id, category_id, name, price) values (247, 24, 'Notepad / Envelopes', 27.2);
insert into product (id, category_id, name, price) values (248, 24, 'Glue / Tape', 23.2);
insert into product (id, category_id, name, price) values (249, 24, 'Printer paper', 18.2);
insert into product (id, category_id, name, price) values (250, 24, 'Pens / Pencils', 18.2);
insert into product (id, category_id, name, price) values (251, 24, 'Postage stamps', 24.2);
insert into product (id, category_id, name, price) values (252, 25, 'Automotive', 11.5);
insert into product (id, category_id, name, price) values (253, 25, 'Batteries', 7.5);
insert into product (id, category_id, name, price) values (254, 25, 'Charcoal / Propane', 15.5);
insert into product (id, category_id, name, price) values (255, 25, 'Flowers / Greeting card', 9.5);
insert into product (id, category_id, name, price) values (256, 25, 'Insect repellent', 12.5);
insert into product (id, category_id, name, price) values (257, 25, 'Light bulbs', 9.5);
insert into product (id, category_id, name, price) values (258, 25, 'Newspaper / Magazine', 8.5);
insert into product (id, category_id, name, price) values (259, 25, 'Random impulse buy', 6.5);
insert into product (id, category_id, name, price) values (260, 26, 'Arsenic', 14.1);
insert into product (id, category_id, name, price) values (261, 26, 'Asbestos', 9.1);
insert into product (id, category_id, name, price) values (262, 26, 'Cigarettes', 9.1);
insert into product (id, category_id, name, price) values (263, 26, 'Radionuclides', 9.1);
insert into product (id, category_id, name, price) values (264, 26, 'Vinyl chloride', 15.1);
